# Generated by Django 5.2.4 on 2025-08-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carinvetory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
